In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [3]:
#Load Libraries for Data Analysis
import os
os.listdir('/kaggle/input/datasets/vincenthope/sentiment2')

['Sentiment.csv']

In [4]:
data = pd.read_csv("/kaggle/input/datasets/vincenthope/sentiment2/Sentiment.csv")
print(data.head())
print(data.info())

   Unnamed: 0.1  Unnamed: 0  \
0             0           0
1             1           1
2             2           2
3             3           3
4             4           4

                                                Text    Sentiment  \
0   Enjoying a beautiful day at the park!        ...   Positive
1   Traffic was terrible this morning.           ...   Negative
2   Just finished an amazing workout! 💪          ...   Positive
3   Excited about the upcoming weekend getaway!  ...   Positive
4   Trying out a new recipe for dinner tonight.  ...   Neutral

             Timestamp            User     Platform  \
0  2023-01-15 12:30:00   User123          Twitter
1  2023-01-15 08:45:00   CommuterX        Twitter
2  2023-01-15 15:45:00   FitnessFan      Instagram
3  2023-01-15 18:20:00   AdventureX       Facebook
4  2023-01-15 19:55:00   ChefCook        Instagram

                                     Hashtags  Retweets  Likes       Country  \
0   #Nature #Park                                  15.0   30.0     USA
1   #Traffic #Morning                               5.0   10.0     Canada
2   #Fitness #Workout                              20.0   40.0   USA
3   #Travel #Adventure                              8.0   15.0     UK
4   #Cooking #Food                                 12.0   25.0    Australia

   Year  Month  Day  Hour
0  2023      1   15    12
1  2023      1   15     8
2  2023      1   15    15
3  2023      1   15    18
4  2023      1   15    19
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    object
 3   Sentiment     732 non-null    object
 4   Timestamp     732 non-null    object
 5   User          732 non-null    object
 6   Platform      732 non-null    object
 7   Hashtags      732 non-null    object
 8   Retweets      732 non-null    float64
 9   Likes         732 non-null    float64
 10  Country       732 non-null    object
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: float64(2), int64(6), object(7)
memory usage: 85.9+ KB
None

In [5]:
# Counting missing values per column
data.isnull().sum()

Unnamed: 0.1    0
Unnamed: 0      0
Text            0
Sentiment       0
Timestamp       0
User            0
Platform        0
Hashtags        0
Retweets        0
Likes           0
Country         0
Year            0
Month           0
Day             0
Hour            0
dtype: int64

In [6]:
# Handle Missing Values
data = data.dropna()

In [11]:
#Encode Categorical Variables

# If your dataset has text labels (e.g., positive/negative):

label_encoder = LabelEncoder()

# Replace 'target_column' with your actual sentiment column name
data['Sentiment'] = label_encoder.fit_transform(data['Sentiment'])

data.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,214,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,195,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,214,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,214,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,197,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [13]:
data = data.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1)
data.head()

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,Enjoying a beautiful day at the park! ...,214,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,Traffic was terrible this morning. ...,195,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,Just finished an amazing workout! 💪 ...,214,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,Excited about the upcoming weekend getaway! ...,214,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,Trying out a new recipe for dinner tonight. ...,197,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

In [14]:
# Separate Features and Target
X = data.drop('Sentiment', axis=1)
y = data['Sentiment']

In [15]:
#Convert Other Categorical Columns (if any)
X = pd.get_dummies(X)

In [17]:
#Feature Scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [18]:
#Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

In [19]:
#Train Models
# Logistic Regression
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

In [20]:
#Decision Tree
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

In [21]:
# Random Forest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

In [23]:
# Evaluation Function
def evaluate_model(y_test, y_pred, model_name):
    print(f"\n{model_name} Performance:")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average='weighted'))
    print("Recall:", recall_score(y_test, y_pred, average='weighted'))
    print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))
    print("\nClassification Report:\n", classification_report(y_test, y_pred))

In [24]:
# Evaluate All Models
evaluate_model(y_test, y_pred_lr, "Logistic Regression")
evaluate_model(y_test, y_pred_dt, "Decision Tree")
evaluate_model(y_test, y_pred_rf, "Random Forest")

Logistic Regression Performance:
Accuracy: 0.1564625850340136
Precision: 0.06838855972496526
Recall: 0.1564625850340136
F1 Score: 0.07458789839823027

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           3       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           9       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          17       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         3
          23       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          30       0.00      0.00      0.00         1
          31       0.00      0.00      0.00         1
          32       0.00      0.00      0.00         1
          33       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          38       0.00      0.00      0.00         1
          40       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         1
          53       0.00      0.00      0.00         3
          54       0.00      0.00      0.00         1
          55       0.00      0.00      0.00         1
          56       0.00      0.00      0.00         3
          57       0.00      0.00      0.00         1
          58       1.00      1.00      1.00         1
          61       0.00      0.00      0.00         1
          64       0.00      0.00      0.00         2
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         2
          71       0.00      0.00      0.00         1
          79       0.00      0.00      0.00         2
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         2
          89       0.00      0.00      0.00         3
          90       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          93       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         1
         100       0.00      0.00      0.00         2
         101       0.00      0.00      0.00         1
         103       0.00      0.00      0.00         2
         104       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         0
         108       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         3
         111       0.00      0.00      0.00         3
         112       0.00      0.00      0.00         1
         115       0.00      0.00      0.00         1
         116       0.00      0.00      0.00         1
         121       0.00      0.00      0.00         1
         122       0.00      0.00      0.00         3
         124       0.00      0.00      0.00         2
         127       1.00      1.00      1.00         1
         135       0.00      0.00      0.00         1
         139       0.00      0.00      0.00         6
         143       0.00      0.00      0.00         2
         145       0.00      0.00      0.00         2
         152       1.00      1.00      1.00         1
         159       0.00      0.00      0.00         1
         162       0.00      0.00      0.00         1
         163       1.00      1.00      1.00         1
         167       0.00      0.00      0.00         1
         169       0.00      0.00      0.00         1
         172       0.09      0.88      0.17         8
         173       0.00      0.00      0.00         1
         175       0.00      0.00      0.00         1
         176       0.00      0.00      0.00         1
         178       1.00      1.00      1.00         1
         180       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         1
         187       0.00      0.00      0.00         2
         191       0.00      0.00      0.00         1
         196       0.00      0.00      0.00         1
         199       0.00      0.00      0.00         1
         201       0.00      0.00      0.00         1
         203       0.00      0.00      0.00         1
         208       0.00      0.00      0.00         1
         211       1.00      0.50      0.67         2
         214       0.15      1.00      0.25         9
         220       1.00      1.00      1.00         1
         224       0.00      0.00      0.00         1
         227       0.00      0.00      0.00         1
         232       0.00      0.00      0.00         1
         234       0.00      0.00      0.00         1
         240       0.00      0.00      0.00         2
         242       0.00      0.00      0.00         1
         243       0.00      0.00      0.00         2
         246       0.00      0.00      0.00         2
         250       0.00      0.00      0.00         1
         252       0.00      0.00      0.00         1
         253       0.00      0.00      0.00         1
         257       0.00      0.00      0.00         1
         264       0.00      0.00      0.00         1
         269       0.00      0.00      0.00         1
         271       0.00      0.00      0.00         1
         278       0.00      0.00      0.00         1

    accuracy                           0.16       147
   macro avg       0.07      0.08      0.07       147
weighted avg       0.07      0.16      0.07       147


Decision Tree Performance:
Accuracy: 0.20408163265306123
Precision: 0.21689342403628117
Recall: 0.20408163265306123
F1 Score: 0.19983934194460512

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         0
           9       1.00      1.00      1.00         1
          12       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          17       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         3
          23       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          28       0.50      1.00      0.67         1
          29       0.00      0.00      0.00         2
          30       0.00      0.00      0.00         1
          31       0.00      0.00      0.00         1
          32       0.00      0.00      0.00         1
          33       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          36       0.00      0.00      0.00         0
          38       0.25      1.00      0.40         1
          40       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         1
          43       0.00      0.00      0.00         0
          45       0.00      0.00      0.00         1
          46       0.00      0.00      0.00         0
          47       0.00      0.00      0.00         0
          50       0.00      0.00      0.00         0
          53       0.00      0.00      0.00         3
          54       0.00      0.00      0.00         1
          55       0.00      0.00      0.00         1
          56       0.00      0.00      0.00         3
          57       0.00      0.00      0.00         1
          58       1.00      1.00      1.00         1
          61       0.00      0.00      0.00         1
          64       0.00      0.00      0.00         2
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         2
          71       0.00      0.00      0.00         1
          73       0.00      0.00      0.00         0
          75       0.00      0.00      0.00         0
          78       0.00      0.00      0.00         0
          79       0.00      0.00      0.00         2
          80       0.00      0.00      0.00         0
          81       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         2
          89       0.00      0.00      0.00         3
          90       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          93       0.00      0.00      0.00         1
          95       0.50      1.00      0.67         1
          96       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         2
         101       0.00      0.00      0.00         1
         102       0.00      0.00      0.00         0
         103       0.00      0.00      0.00         2
         104       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         0
         108       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         3
         111       0.00      0.00      0.00         3
         112       0.00      0.00      0.00         1
         114       0.00      0.00      0.00         0
         115       1.00      1.00      1.00         1
         116       0.00      0.00      0.00         1
         118       0.00      0.00      0.00         0
         121       1.00      1.00      1.00         1
         122       0.00      0.00      0.00         3
         124       0.00      0.00      0.00         2
         127       1.00      1.00      1.00         1
         128       0.00      0.00      0.00         0
         131       0.00      0.00      0.00         0
         135       0.00      0.00      0.00         1
         136       0.00      0.00      0.00         0
         139       1.00      0.50      0.67         6
         143       0.00      0.00      0.00         2
         145       0.00      0.00      0.00         2
         148       0.00      0.00      0.00         0
         152       1.00      1.00      1.00         1
         156       0.00      0.00      0.00         0
         158       0.00      0.00      0.00         0
         159       0.00      0.00      0.00         1
         162       0.00      0.00      0.00         1
         163       1.00      1.00      1.00         1
         167       0.00      0.00      0.00         1
         169       0.00      0.00      0.00         1
         170       0.00      0.00      0.00         0
         171       0.00      0.00      0.00         0
         172       0.20      0.12      0.15         8
         173       0.00      0.00      0.00         1
         175       0.00      0.00      0.00         1
         176       1.00      1.00      1.00         1
         177       0.00      0.00      0.00         0
         178       0.50      1.00      0.67         1
         179       0.00      0.00      0.00         0
         180       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         1
         187       1.00      0.50      0.67         2
         191       0.00      0.00      0.00         1
         195       0.00      0.00      0.00         0
         196       1.00      1.00      1.00         1
         198       0.00      0.00      0.00         0
         199       0.00      0.00      0.00         1
         201       0.33      1.00      0.50         1
         203       0.00      0.00      0.00         1
         206       0.00      0.00      0.00         0
         208       0.00      0.00      0.00         1
         210       0.00      0.00      0.00         0
         211       1.00      0.50      0.67         2
         214       0.80      0.89      0.84         9
         220       1.00      1.00      1.00         1
         223       0.00      0.00      0.00         0
         224       0.00      0.00      0.00         1
         227       0.00      0.00      0.00         1
         232       0.00      0.00      0.00         1
         234       0.00      0.00      0.00         1
         236       0.00      0.00      0.00         0
         238       0.00      0.00      0.00         0
         239       0.00      0.00      0.00         0
         240       0.00      0.00      0.00         2
         242       0.00      0.00      0.00         1
         243       0.00      0.00      0.00         2
         244       0.00      0.00      0.00         0
         246       0.00      0.00      0.00         2
         250       0.00      0.00      0.00         1
         252       0.00      0.00      0.00         1
         253       0.00      0.00      0.00         1
         256       0.00      0.00      0.00         0
         257       1.00      1.00      1.00         1
         260       0.00      0.00      0.00         0
         263       0.00      0.00      0.00         0
         264       0.00      0.00      0.00         1
         267       0.00      0.00      0.00         0
         269       0.00      0.00      0.00         1
         271       0.00      0.00      0.00         1
         273       0.00      0.00      0.00         0
         278       0.00      0.00      0.00         1

    accuracy                           0.20       147
   macro avg       0.12      0.13      0.12       147
weighted avg       0.22      0.20      0.20       147


Random Forest Performance:
Accuracy: 0.20408163265306123
Precision: 0.20162509448223734
Recall: 0.20408163265306123
F1 Score: 0.1764031417796372

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           9       1.00      1.00      1.00         1
          12       0.00      0.00      0.00         1
          15       1.00      1.00      1.00         1
          17       0.00      0.00      0.00         1
          19       0.00      0.00      0.00         0
          21       0.00      0.00      0.00         0
          22       0.00      0.00      0.00         3
          23       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          30       0.00      0.00      0.00         1
          31       1.00      1.00      1.00         1
          32       0.00      0.00      0.00         1
          33       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          37       0.00      0.00      0.00         0
          38       1.00      1.00      1.00         1
          40       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         1
          50       0.00      0.00      0.00         0
          53       1.00      0.67      0.80         3
          54       0.00      0.00      0.00         1
          55       0.00      0.00      0.00         1
          56       0.00      0.00      0.00         3
          57       0.00      0.00      0.00         1
          58       1.00      1.00      1.00         1
          61       0.00      0.00      0.00         1
          64       0.00      0.00      0.00         2
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         1
          68       0.00      0.00      0.00         2
          70       0.00      0.00      0.00         0
          71       0.00      0.00      0.00         1
          72       0.00      0.00      0.00         0
          78       0.00      0.00      0.00         0
          79       0.00      0.00      0.00         2
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         2
          89       0.00      0.00      0.00         3
          90       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          92       0.00      0.00      0.00         0
          93       0.00      0.00      0.00         1
          95       0.00      0.00      0.00         1
          99       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         2
         101       0.00      0.00      0.00         1
         103       0.00      0.00      0.00         2
         104       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         0
         108       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         3
         111       0.00      0.00      0.00         3
         112       0.00      0.00      0.00         1
         115       1.00      1.00      1.00         1
         116       0.00      0.00      0.00         1
         118       0.00      0.00      0.00         0
         121       1.00      1.00      1.00         1
         122       0.00      0.00      0.00         3
         124       0.00      0.00      0.00         2
         127       0.50      1.00      0.67         1
         128       0.00      0.00      0.00         0
         132       0.00      0.00      0.00         0
         133       0.00      0.00      0.00         0
         135       0.00      0.00      0.00         1
         139       1.00      0.17      0.29         6
         143       0.00      0.00      0.00         2
         145       0.00      0.00      0.00         2
         151       0.00      0.00      0.00         0
         152       1.00      1.00      1.00         1
         156       0.00      0.00      0.00         0
         158       0.00      0.00      0.00         0
         159       0.00      0.00      0.00         1
         162       0.00      0.00      0.00         1
         163       0.50      1.00      0.67         1
         167       0.00      0.00      0.00         1
         169       0.00      0.00      0.00         1
         170       0.00      0.00      0.00         0
         172       0.11      0.25      0.15         8
         173       0.00      0.00      0.00         1
         175       0.00      0.00      0.00         1
         176       0.00      0.00      0.00         1
         178       0.50      1.00      0.67         1
         180       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         1
         187       0.00      0.00      0.00         2
         190       0.00      0.00      0.00         0
         191       0.00      0.00      0.00         1
         196       0.00      0.00      0.00         1
         199       0.00      0.00      0.00         1
         201       0.20      1.00      0.33         1
         203       0.00      0.00      0.00         1
         204       0.00      0.00      0.00         0
         208       0.00      0.00      0.00         1
         211       1.00      0.50      0.67         2
         214       0.45      1.00      0.62         9
         217       0.00      0.00      0.00         0
         220       1.00      1.00      1.00         1
         224       0.00      0.00      0.00         1
         225       0.00      0.00      0.00         0
         227       0.00      0.00      0.00         1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [26]:
# Hyperparameter Tuning (Grid Search)
# Random Forest Tuning
param_grid = {
    'n_estimators': [50, 100],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5]
}

grid = GridSearchCV(RandomForestClassifier(), param_grid, cv=3, scoring='f1_weighted')
grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(

Best Parameters: {'max_depth': None, 'min_samples_split': 2, 'n_estimators': 100}

In [27]:
# Evaluate Best Model
best_model = grid.best_estimator_
y_pred_best = best_model.predict(X_test)

evaluate_model(y_test, y_pred_best, "Tuned Random Forest")

Tuned Random Forest Performance:
Accuracy: 0.20408163265306123
Precision: 0.15759935553168636
Recall: 0.20408163265306123
F1 Score: 0.16005176481366956

Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         1
          12       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          17       0.00      0.00      0.00         1
          22       0.00      0.00      0.00         3
          23       0.00      0.00      0.00         0
          24       0.00      0.00      0.00         1
          26       0.00      0.00      0.00         1
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         2
          30       0.00      0.00      0.00         1
          31       1.00      1.00      1.00         1
          32       0.00      0.00      0.00         1
          33       0.00      0.00      0.00         1
          35       0.00      0.00      0.00         1
          37       0.00      0.00      0.00         0
          38       1.00      1.00      1.00         1
          40       0.00      0.00      0.00         1
          42       0.00      0.00      0.00         1
          45       0.00      0.00      0.00         1
          53       0.00      0.00      0.00         3
          54       0.00      0.00      0.00         1
          55       0.00      0.00      0.00         1
          56       0.00      0.00      0.00         3
          57       0.00      0.00      0.00         1
          58       1.00      1.00      1.00         1
          61       0.00      0.00      0.00         1
          64       0.00      0.00      0.00         2
          65       0.00      0.00      0.00         0
          66       0.00      0.00      0.00         1
          68       0.50      0.50      0.50         2
          70       0.00      0.00      0.00         0
          71       0.00      0.00      0.00         1
          72       0.00      0.00      0.00         0
          73       0.00      0.00      0.00         0
          78       0.00      0.00      0.00         0
          79       0.00      0.00      0.00         2
          80       0.00      0.00      0.00         0
          82       0.00      0.00      0.00         1
          83       0.00      0.00      0.00         2
          89       0.50      0.33      0.40         3
          90       0.00      0.00      0.00         1
          91       0.00      0.00      0.00         1
          92       0.00      0.00      0.00         0
          93       0.00      0.00      0.00         1
          95       0.25      1.00      0.40         1
          99       0.00      0.00      0.00         0
         100       0.00      0.00      0.00         2
         101       0.00      0.00      0.00         1
         103       0.00      0.00      0.00         2
         104       0.00      0.00      0.00         1
         107       0.00      0.00      0.00         0
         108       0.00      0.00      0.00         1
         110       0.00      0.00      0.00         3
         111       0.00      0.00      0.00         3
         112       0.00      0.00      0.00         1
         115       0.00      0.00      0.00         1
         116       0.00      0.00      0.00         1
         118       0.00      0.00      0.00         0
         121       0.00      0.00      0.00         1
         122       0.00      0.00      0.00         3
         124       0.00      0.00      0.00         2
         125       0.00      0.00      0.00         0
         127       1.00      1.00      1.00         1
         128       0.00      0.00      0.00         0
         130       0.00      0.00      0.00         0
         132       0.00      0.00      0.00         0
         135       0.00      0.00      0.00         1
         136       0.00      0.00      0.00         0
         139       0.50      0.17      0.25         6
         143       0.00      0.00      0.00         2
         145       0.00      0.00      0.00         2
         147       0.00      0.00      0.00         0
         151       0.00      0.00      0.00         0
         152       0.50      1.00      0.67         1
         158       0.00      0.00      0.00         0
         159       0.00      0.00      0.00         1
         160       0.00      0.00      0.00         0
         162       0.00      0.00      0.00         1
         163       0.50      1.00      0.67         1
         167       0.00      0.00      0.00         1
         169       0.00      0.00      0.00         1
         172       0.11      0.25      0.15         8
         173       0.00      0.00      0.00         1
         175       0.00      0.00      0.00         1
         176       1.00      1.00      1.00         1
         178       0.50      1.00      0.67         1
         180       0.00      0.00      0.00         1
         182       0.00      0.00      0.00         1
         187       0.00      0.00      0.00         2
         190       0.00      0.00      0.00         0
         191       0.00      0.00      0.00         1
         194       0.00      0.00      0.00         0
         196       0.00      0.00      0.00         1
         198       0.00      0.00      0.00         0
         199       0.00      0.00      0.00         1
         201       0.20      1.00      0.33         1
         203       0.50      1.00      0.67         1
         208       0.00      0.00      0.00         1
         211       1.00      0.50      0.67         2
         214       0.38      1.00      0.55         9
         216       0.00      0.00      0.00         0
         217       0.00      0.00      0.00         0
         220       1.00      1.00      1.00         1
         224       0.00      0.00      0.00         1
         225       0.00      0.00      0.00         0
         227       0.00      0.00      0.00         1
         232       0.00      0.00      0.00         1
         234       0.00      0.00      0.00         1
         239       0.00      0.00      0.00         0
         240       0.00      0.00      0.00         2
         242       0.00      0.00      0.00         1
         243       0.00      0.00      0.00         2
         246       1.00      1.00      1.00         2
         250       0.00      0.00      0.00         1
         252       0.00      0.00      0.00         1
         253       0.00      0.00      0.00         1
         257       1.00      1.00      1.00         1
         264       0.00      0.00      0.00         1
         267       0.00      0.00      0.00         0
         269       0.00      0.00      0.00         1
         271       0.00      0.00      0.00         1
         278       0.00      0.00      0.00         1

    accuracy                           0.20       147
   macro avg       0.10      0.13      0.11       147
weighted avg       0.16      0.20      0.16       147

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))